### ISSUE TITLE
No attribute 'setmode'

### ISSUE THREAD

**Issue by ccesario** [adafruit/Adafruit_Python_GPIO#14]
Hello,
I 'm testing this lib, but or my code is wrong or can be a bug :)

```
import Adafruit_GPIO as GPIO
GPIO.setmode(GPIO.BCM)
```

This code cause error

```
Traceback (most recent call last):
  File "text.py", line 2, in <module>
    GPIO.setmode(GPIO.BCM)
AttributeError: 'module' object has no attribute 'setmode'
```

Does someone have idea ? 

Regards,

Carlos

**Comment by tdicola** [comment]
One other major difference is with PWM.  This library has an interface that looks like the BBIO library's PWM functions.  You can see the interface here if you're curious: https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/PWM.py

I have some time free and will add the cleanup function shortly now too.

**Comment by tdicola** [comment]
Just merged in a cleanup function, grab the latest library and install it with the --force option to make sure it's reinstalled:
````
sudo python setup.py install --force
````
Thanks for suggesting the change!

**Comment by rakell** [comment]
I just stumbled onto this courtesy  of Mr. Google.  Thanks to this thread, I was able to get access to my Pi3's onboard gpio pins and get an LED to flash

What I'm wondering now is whether the Adafruit_GPIO library can be used to access the onboad gpio pins along with those on the MCP23017.

Using this little bit of code, I have been able to turn on and turn off and LED attached to the MCP23017

import Adafruit_GPIO as GPIO
from Adafruit_GPIO import MCP230xx as MCP
mcp = MCP.MCP23017(address = 32)

LED = 0

mcp.setup(LED, GPIO.OUT)
 mcp.output(LED, 1)
 time.sleep(0.5)
 mcp.output(LED, 0)

# Cleanup

mcp.output(LED,0)
mcp.setup(LED,1)


I hope this is clear enough.   Thanks for your help.
