### ISSUE TITLE
Add GPIO cleanup function.

### ISSUE THREAD

**Issue by tdicola** [adafruit/Adafruit_Python_GPIO#15]
Now that there's event detection logic we should add a cleanup function to the GPIO base class and have it call the appropriate Pi, BBB, etc. library cleanup.  See #14

**Comment by tdicola** [comment]
This is fixed with this commit: https://github.com/adafruit/Adafruit_Python_GPIO/commit/4f2ea8342fcf4129a66a22b3020d85bb67108f45

**Comment by ccesario** [comment]
Thank you @tdicola !!!
