### ISSUE TITLE
Building community

### ISSUE THREAD

**Issue by asomov** [adafruit/Adafruit_Python_GPIO#19]
a few steps can help to build a community for this project:
1) How to contact developers ? Is there a maling list ? (Google should help to make it a reference documentation in the future.)
2)  Description of how to develop code should be very useful. How to launch tests (I got an error: "ImportError: No module named mock") ? Do you use remote development (PyCharm Pro)
3) wiki can help to share and support the documentation for usage and developmenbt

**Comment by tdicola** [comment]
Thanks for the feedback and great ideas.  I think for now the best place to collaborate on it is here on github with issue, comments, wiki, etc.

Great point about tests--let me update the readme to put in a little more info about running them.  Yep you'll want to install the mock library (`pip install mock` is the easiest way to get it if you have pip installed).  No need to run the tests on a Pi, BeagleBone Black, etc. as they use a lot of mocking to imitate platform-specific setup.
