### ISSUE TITLE
Alternating variable name in I2C.py

### ISSUE THREAD

**Issue by jamieisboss** [adafruit/Adafruit_Python_GPIO#45]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  

Ubuntu 16.04 but i havent run the code yet, pylint just picked up the unused variable
- Python version (run `python -version` or `python3 -version`):  3.5.1+
- Error message you are receiving, including any Python exception traces:  

`Pylint Warning W0612 Unused variable 'i' at line 33 col 8 in Adafruit_GPIO/I2C.py`
- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 

here's the section

```
 def reverseByteOrder(data):
 """Reverses the byte order of an int (16-bit) or long (32-bit) value."""
 # Courtesy Vishal Sapre
 byteCount = len(hex(data)[2:].replace('L','')[::2])
  val       = 0
  for i in range(byteCount):
      val    = (val << 8) | (data & 0xff)
      data >>= 8
   return val
```

It's a counter, there's a  variable declared, `val`, then in the for statement `i` is used but only in the first line after which `val` is used again

Like I say I opened the file in atom to have a look and pylint pointed it out, (also a bunch of convention messages about the method names being in camelcase when they should be separated with underscores but, that's not gonna break anything and when it gives me an option to auto fix them, i'll happily let that fix it and you'll see a PR :put_litter_in_its_place: )

The variable name thing i thought I'd mention it looks like it should break that function, probably without an error. My Python's not great though but if it doesn't break it I'd love to understand why, it's been there since the code has been on github and it's not been fixed so either that function isn't used much (at all?) or I'm going to learn something.

So in advance return, like a knowledge exchange, the unambiguous name for this symbol :hash: is an octothorpe, the origin is strange but it is the same as the origin of the word sextile \* (six points)

**Comment by tdicola** [comment]
Yeah that reverse bytes function was problematic and inherited from some legacy code.  In practice none of the library code depended on it and instead used struct and other modules for explicit big/little endian conversion.  Since then the function was commented out and raises an exception with this change: https://github.com/adafruit/Adafruit_Python_GPIO/issues/48  So I'll close this issue as the function isn't supported or used anymore.
