### ISSUE TITLE
nvidia Jetson TX1 support

### ISSUE THREAD

**Issue by shoemakerlevy9** [adafruit/Adafruit_Python_GPIO#54]
[proposed Label] enhancement

I am running this library on a TX1 along with the Adafruit_Python_ADS1x15 library in order to use the ADS1015 chip through the built in I2C port. 

I modified the I2C.py file, replaced the raise on line 55 with a return 0 and it works, which suggests that the default I2C bus on the TX1 board is 0 (like the original raspberry pi). 

If support for the TX1 where added to the platform_detect() function then the I2C bus could be dynamically set here.

**Comment by tdicola** [comment]
Oh interesting, that's cool you're trying out the Jetson board!  I'm going to close this though as it's not really tracking a defect or problem with the library.  Thanks!

**Comment by sharoseali** [comment]
@shoemakerlevy9  can u completely explain how u modify this code for TX1??? i want to use it with TX2 i need Your help....
