### ISSUE TITLE
Version 1.0.2 not uploaded to PyPi

### ISSUE THREAD

**Issue by chrisb2** [adafruit/Adafruit_Python_GPIO#59]
Please can you upload version 1.0.2 to PyPi, which currently only has the previous version (1.0.1):

[https://pypi.python.org/pypi/Adafruit-GPIO](https://pypi.python.org/pypi/Adafruit-GPIO)

thanks,
Chris

**Comment by e10kstarfire** [comment]
Yes, please can this be pushed to PyPi as I struggled for a long time trying to figure out why it was still failing on RPi detecting the platform when I see it was fixed, until I realised it hadn't been uploaded

**Comment by slokhorst** [comment]
Yes please. #60 is a critical bug which isn't fixed on PyPi.

**Comment by tdicola** [comment]
The latest version is up on pypi now, thanks!
