### ISSUE TITLE
Incorrect detection of Raspberry Pi version

### ISSUE THREAD

**Issue by ameer1234567890** [adafruit/Adafruit_Python_GPIO#65]
Platform.py detects Raspberry Pi version on Kernel 4.9 incorrectly. It assumes BCM2708 as Pi 1, BCM2709 as Pi 2 and BCM2835 as Pi 3. In contrast BCM2835 is Pi 1, BCM2836 is Pi 2 and BCM2837 is Pi 3 on kernel 4.9.

**Comment by arcSlayer85** [comment]
could this be why my lcd code thinks my RPi 2B needs a BeagleBone GPIO module? when it doesn't

**Comment by slokhorst** [comment]
My Pi 2 is listed as `BCM2835` in kernel 4.9.

**Comment by ladyada** [comment]
btw Pi 2's now come with a Pi 3 chipset so they're essentially a Pi 3 minus BT/WiFi

**Comment by tdicola** [comment]
@arcSlayer85 Make sure to update the library to the latest version, #60 fixed the kernel detection issue.  Check the bug for details on how to force an upgrade in case you've got an older version of the library and python doesn't want to update it.

Also the original issue from @ameer1234567890 should be resolved with #60 too.  For anyone running into an error make sure to download and reinstall the GPIO library with the force option like #60 mentions.
