### ISSUE TITLE
Platform.pi_version() regex fails

### ISSUE THREAD

**Issue by elevenchars** [adafruit/Adafruit_Python_GPIO#72]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  **INSERT PLATFORM/OPERATING
  SYSTEM HERE**
rpi 3 running jessie
- Python version (run `python -version` or `python3 -version`):  **INSERT PYTHON
  VERSION HERE**

2.7.9

- Error message you are receiving, including any Python exception traces:  **INSERT
  ERROR MESAGE/EXCEPTION TRACES HERE***

whenever i run Platform.pi_version(), it returns None, which led me to think that the regex was not parsing the info from /proc/cpuinfo properly. i was able to get it to grab the hardware group properly by changing the regex to this:
`Hardware\\t+:\s+(\w+)`
When re.match parses cpuinfo it reads in the escaped characters. I am sure there is a more elegant solution but I am not familiar enough with python to parse cpuinfo with the characters unescaped.

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**

run Platform.pi_version()

**Comment by tdicola** [comment]
This was fixed last year with a few other changes--trying the platform pi_version function now returns the correct version.  Thanks for raising the issue!
