### ISSUE TITLE
Support for Jetson TX2

### ISSUE THREAD

**Issue by sharoseali** [adafruit/Adafruit_Python_GPIO#89]
how can i edit the these files to make support for Jetson TX2

**Comment by ladyada** [comment]
we'd actually rather have support added here - we'll be supporting circuitpython for sensors/devices only going forward. 
https://github.com/adafruit/Adafruit_Blinka

we don't have a tutorial on how to add more support, but there's a general guide here:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/
